{
 "title": "Node Exporter Full",
 "tags": [
  "node_exporter",
  "system",
  "linux",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{job=\"node_exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick CPU / Mem / Disk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])) * 100)"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100)"
    }
   ]
  },
  { "title": "CPU / Memory / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])) * 100)",
     "legendFormat": "Busy System"
    },
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"system\"}[$__interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"user\"}[$__interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"iowait\"}[$__interval])) * 100",
     "legendFormat": "Busy I/O"
    },
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"irq\"}[$__interval])) * 100",
     "legendFormat": "Busy IRQ"
    },
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"softirq\"}[$__interval])) * 100",
     "legendFormat": "Busy SoftIRQ"
    },
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"steal\"}[$__interval])) * 100",
     "legendFormat": "Busy Steal"
    },
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"guest\"}[$__interval])) * 100",
     "legendFormat": "Busy Guest"
    },
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"guest_nice\"}[$__interval])) * 100",
     "legendFormat": "Busy Guest Nice"
    },
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"nice\"}[$__interval])) * 100",
     "legendFormat": "Busy Nice"
    },
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes",
     "legendFormat": "Total - Used"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Cache + Buffer" },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "Swap Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total[$__interval]))",
     "legendFormat": "Rx ({{instance}})"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total[$__interval]))",
     "legendFormat": "Tx ({{instance}})"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100)",
     "legendFormat": "/ ({{instance}})"
    },
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/boot\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/boot\",fstype!=\"rootfs\"} * 100)",
     "legendFormat": "/boot ({{instance}})"
    },
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/home\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/home\",fstype!=\"rootfs\"} * 100)",
     "legendFormat": "/home ({{instance}})"
    },
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/tmp\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/tmp\",fstype!=\"rootfs\"} * 100)",
     "legendFormat": "/tmp ({{instance}})"
    },
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/var\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/var\",fstype!=\"rootfs\"} * 100)",
     "legendFormat": "/var ({{instance}})"
    },
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/usr\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/usr\",fstype!=\"rootfs\"} * 100)",
     "legendFormat": "/usr ({{instance}})"
    },
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/opt\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/opt\",fstype!=\"rootfs\"} * 100)",
     "legendFormat": "/opt ({{instance}})"
    },
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/snap\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/snap\",fstype!=\"rootfs\"} * 100)",
     "legendFormat": "/snap ({{instance}})"
    },
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/var/lib/docker/overlay2\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/var/lib/docker/overlay2\",fstype!=\"rootfs\"} * 100)",
     "legendFormat": "/var/lib/docker/overlay2 ({{instance}})"
    },
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/mnt/wslg\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/mnt/wslg\",fstype!=\"rootfs\"} * 100)",
     "legendFormat": "/mnt/wslg ({{instance}})"
    },
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/run/user/1000/gvfs\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/run/user/1000/gvfs\",fstype!=\"rootfs\"} * 100)",
     "legendFormat": "/run/user/1000/gvfs ({{instance}})"
    }
   ]
  }
 ]
}